development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: video_development
  pool: 5
  username: root
  password: pass
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: video_test
  pool: 5
  username: root
  password: pass
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: video_production
  pool: 5
  username: root
  password: pass
  socket: /tmp/mysql.sock
